// <auto-generated />
using System;
using E_learning_Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_learning_Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("E_learning_Api.Models.About", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Abouts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6770),
                            Description = "Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos. Clita erat ipsum et lorem et sit.Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos. Clita erat ipsum et lorem et sit, sed stet lorem sit clita duo justo magna dolore erat amet",
                            Image = "about.jpg",
                            SoftDeleted = false,
                            Title = "Welcome to eLEARNING"
                        });
                });

            modelBuilder.Entity("E_learning_Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6780),
                            Image = "cat-1.jpg",
                            Name = "Web Design",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6790),
                            Image = "cat-2.jpg",
                            Name = "Graphic Design",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6790),
                            Image = "cat-3.jpg",
                            Name = "Video Editing",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6790),
                            Image = "cat-4.jpg",
                            Name = "Online Marketing",
                            SoftDeleted = false
                        });
                });

            modelBuilder.Entity("E_learning_Api.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("E_learning_Api.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6950),
                            Description = "Hello",
                            EndDate = new DateTime(2024, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 1,
                            Name = "Ux-Ui",
                            Price = 200m,
                            Rating = 10,
                            SoftDeleted = false,
                            StartDate = new DateTime(2024, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6950),
                            Description = "Hello",
                            EndDate = new DateTime(2024, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 2,
                            Name = "Graphic",
                            Price = 300m,
                            Rating = 15,
                            SoftDeleted = false,
                            StartDate = new DateTime(2024, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6950),
                            Description = "Hello",
                            EndDate = new DateTime(2024, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 2,
                            Name = "Front-End",
                            Price = 100m,
                            Rating = 10,
                            SoftDeleted = false,
                            StartDate = new DateTime(2024, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6960),
                            Description = "Hello",
                            EndDate = new DateTime(2024, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 5,
                            Name = "Editor",
                            Price = 400m,
                            Rating = 20,
                            SoftDeleted = false,
                            StartDate = new DateTime(2024, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("E_learning_Api.Models.CourseImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            IsMain = true,
                            Name = "course-1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            IsMain = false,
                            Name = "course-2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 2,
                            IsMain = false,
                            Name = "course-3.jpg"
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 2,
                            IsMain = true,
                            Name = "course-1.jpg"
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 3,
                            IsMain = false,
                            Name = "course-2.jpg"
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 3,
                            IsMain = true,
                            Name = "course-1.jpg"
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 4,
                            IsMain = true,
                            Name = "course-1.jpg"
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 4,
                            IsMain = false,
                            Name = "course-2.jpg"
                        });
                });

            modelBuilder.Entity("E_learning_Api.Models.CourseStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("CourseStudents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 2,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6970),
                            SoftDeleted = false,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6970),
                            SoftDeleted = false,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 2,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6970),
                            SoftDeleted = false,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 2,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6970),
                            SoftDeleted = false,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 1,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6980),
                            SoftDeleted = false,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 3,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6980),
                            SoftDeleted = false,
                            StudentId = 2
                        });
                });

            modelBuilder.Entity("E_learning_Api.Models.Icon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClassName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Icons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassName = "fa fa-3x fa-graduation-cap",
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6820),
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            ClassName = "fa fa-3x fa-globe",
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6820),
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            ClassName = "fa fa-3x fa-home",
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6820),
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            ClassName = "fa fa-3x fa-book-open",
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6820),
                            SoftDeleted = false
                        });
                });

            modelBuilder.Entity("E_learning_Api.Models.Information", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IconId")
                        .HasColumnType("int");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IconId");

                    b.ToTable("Informations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6840),
                            Description = "Diam elitr kasd sed at elitr sed ipsum justo dolor sed clita amet diam",
                            IconId = 1,
                            SoftDeleted = false,
                            Title = "Skilled Instructors"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6840),
                            Description = "Diam elitr kasd sed at elitr sed ipsum justo dolor sed clita amet diam",
                            IconId = 2,
                            SoftDeleted = false,
                            Title = "Online Classes"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6840),
                            Description = "Diam elitr kasd sed at elitr sed ipsum justo dolor sed clita amet diam",
                            IconId = 3,
                            SoftDeleted = false,
                            Title = "Home Projects"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6840),
                            Description = "Diam elitr kasd sed at elitr sed ipsum justo dolor sed clita amet diam",
                            IconId = 4,
                            SoftDeleted = false,
                            Title = "Book Library"
                        });
                });

            modelBuilder.Entity("E_learning_Api.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6850),
                            FullName = "John Doe",
                            Image = "team-1.jpg",
                            Position = "Web Designer",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6860),
                            FullName = "Angelina Jolie",
                            Image = "team-2.jpg",
                            Position = "Graphic Designer",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6860),
                            FullName = "Jake Oliver",
                            Image = "team-3.jpg",
                            Position = "Video Editor",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6860),
                            FullName = "Emily Prior",
                            Image = "team-4.jpg",
                            Position = "SMM Manager",
                            SoftDeleted = false
                        });
                });

            modelBuilder.Entity("E_learning_Api.Models.InstructorSocialMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("SocialLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SocialMediaId")
                        .HasColumnType("int");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.HasIndex("SocialMediaId");

                    b.ToTable("InstructorSocialMedias");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6880),
                            InstructorId = 1,
                            SocialLink = "https://www.instagram.com/angelinajolie?igsh=MWRtOGVqaHJ0YTM2bg==",
                            SocialMediaId = 1,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 101,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6890),
                            InstructorId = 1,
                            SocialLink = "https://www.facebook.com",
                            SocialMediaId = 2,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 102,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6890),
                            InstructorId = 1,
                            SocialLink = "https://x.com",
                            SocialMediaId = 3,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 103,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6890),
                            InstructorId = 2,
                            SocialLink = "https://www.instagram.com/angelinajolie?igsh=MWRtOGVqaHJ0YTM2bg==",
                            SocialMediaId = 1,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 104,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6890),
                            InstructorId = 2,
                            SocialLink = "https://www.facebook.com",
                            SocialMediaId = 2,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 105,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6890),
                            InstructorId = 2,
                            SocialLink = "https://x.com",
                            SocialMediaId = 3,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 106,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6900),
                            InstructorId = 3,
                            SocialLink = "https://www.instagram.com/angelinajolie?igsh=MWRtOGVqaHJ0YTM2bg==",
                            SocialMediaId = 1,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 107,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6900),
                            InstructorId = 3,
                            SocialLink = "https://www.facebook.com",
                            SocialMediaId = 2,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 108,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6900),
                            InstructorId = 3,
                            SocialLink = "https://x.com",
                            SocialMediaId = 3,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 109,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6910),
                            InstructorId = 4,
                            SocialLink = "https://www.instagram.com/angelinajolie?igsh=MWRtOGVqaHJ0YTM2bg==",
                            SocialMediaId = 1,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 110,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6910),
                            InstructorId = 4,
                            SocialLink = "https://www.facebook.com",
                            SocialMediaId = 2,
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 111,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6910),
                            InstructorId = 4,
                            SocialLink = "https://x.com",
                            SocialMediaId = 3,
                            SoftDeleted = false
                        });
                });

            modelBuilder.Entity("E_learning_Api.Models.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1000,
                            Key = "Address",
                            Value = "123 Street, New York, USA"
                        },
                        new
                        {
                            Id = 1001,
                            Key = "Phone Number",
                            Value = "+012 345 67890"
                        },
                        new
                        {
                            Id = 1002,
                            Key = "Email",
                            Value = "fatimaeg@code.edu.az"
                        },
                        new
                        {
                            Id = 1003,
                            Key = "GetInTouch",
                            Value = "The contact form is currently inactive. Get a functional and working contact form with Ajax & PHP in a few minutes. Just copy and paste the files, add a little code and you're done. "
                        },
                        new
                        {
                            Id = 1004,
                            Key = "Twitter",
                            Value = "https://x.com/ "
                        },
                        new
                        {
                            Id = 1005,
                            Key = "Facebook",
                            Value = "https://www.facebook.com/?locale=az_AZ"
                        },
                        new
                        {
                            Id = 1006,
                            Key = "Youtube",
                            Value = "https://www.youtube.com/ "
                        },
                        new
                        {
                            Id = 1007,
                            Key = "Instagram",
                            Value = "https://www.instagram.com/"
                        });
                });

            modelBuilder.Entity("E_learning_Api.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sliders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6710),
                            Description = "Vero elitr justo clita lorem. Ipsum dolor at sed stet sit diam no. Kasd rebum ipsum et diam justo clita et kasd rebum sea sanctus eirmod elitr.",
                            Image = "carousel-1.jpg",
                            SoftDeleted = false,
                            Subject = "Best Online Courses",
                            Title = "The Best Online Learning Platform"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6720),
                            Description = "Vero elitr justo clita lorem. Ipsum dolor at sed stet sit diam no. Kasd rebum ipsum et diam justo clita et kasd rebum sea sanctus eirmod elitr.",
                            Image = "carousel-2.jpg",
                            SoftDeleted = false,
                            Subject = "Best Online Courses",
                            Title = "Get Educated Online From Your Home"
                        });
                });

            modelBuilder.Entity("E_learning_Api.Models.SocialMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("SocialMedias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6870),
                            Icon = "fab fa-instagram",
                            Name = "Instagram",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6870),
                            Icon = "fab fa-facebook-f",
                            Name = "Facebook",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6870),
                            Icon = "fab fa-twitter",
                            Name = "Twitter",
                            SoftDeleted = false
                        });
                });

            modelBuilder.Entity("E_learning_Api.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profession")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6930),
                            Description = "Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit diam amet diam et eos. Clita erat ipsum et lorem et sit.",
                            FullName = "James Beaufort",
                            Image = "testimonial-1.jpg",
                            Profession = "IT",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6930),
                            Description = "Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit diam amet diam et eos. Clita erat ipsum et lorem et sit.",
                            FullName = "Lydia Beaufort",
                            Image = "testimonial-2.jpg",
                            Profession = "Designer",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6930),
                            Description = "Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit diam amet diam et eos. Clita erat ipsum et lorem et sit.",
                            FullName = "Max Beaufort",
                            Image = "testimonial-3.jpg",
                            Profession = "SMM",
                            SoftDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 6, 23, 20, 45, 7, 159, DateTimeKind.Local).AddTicks(6930),
                            Description = "Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit diam amet diam et eos. Clita erat ipsum et lorem et sit.",
                            FullName = "Ruby Beaufort",
                            Image = "testimonial-4.jpg",
                            Profession = "Programmer",
                            SoftDeleted = false
                        });
                });

            modelBuilder.Entity("E_learning_Api.Models.Course", b =>
                {
                    b.HasOne("E_learning_Api.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_learning_Api.Models.Instructor", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("E_learning_Api.Models.CourseImage", b =>
                {
                    b.HasOne("E_learning_Api.Models.Course", "Course")
                        .WithMany("CourseImages")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("E_learning_Api.Models.CourseStudent", b =>
                {
                    b.HasOne("E_learning_Api.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_learning_Api.Models.Student", "Student")
                        .WithMany("CourseStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("E_learning_Api.Models.Information", b =>
                {
                    b.HasOne("E_learning_Api.Models.Icon", "Icon")
                        .WithMany()
                        .HasForeignKey("IconId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Icon");
                });

            modelBuilder.Entity("E_learning_Api.Models.InstructorSocialMedia", b =>
                {
                    b.HasOne("E_learning_Api.Models.Instructor", "Instructor")
                        .WithMany("InstructorSocialMedias")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_learning_Api.Models.SocialMedia", "SocialMedia")
                        .WithMany()
                        .HasForeignKey("SocialMediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");

                    b.Navigation("SocialMedia");
                });

            modelBuilder.Entity("E_learning_Api.Models.Course", b =>
                {
                    b.Navigation("CourseImages");
                });

            modelBuilder.Entity("E_learning_Api.Models.Instructor", b =>
                {
                    b.Navigation("InstructorSocialMedias");
                });

            modelBuilder.Entity("E_learning_Api.Models.Student", b =>
                {
                    b.Navigation("CourseStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
